#DOCKER_COMPOSE = '''
version: '3.8'

services:
  smartnodule-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./models:/app/models
      - ./case_retrieval:/app/case_retrieval
      - ./logs:/app/logs
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: >
      sh -c "pip install mlflow &&
             mlflow server 
             --backend-store-uri sqlite:///mlflow/mlflow.db
             --default-artifact-root /mlflow/artifacts
             --host 0.0.0.0
             --port 5000"
    restart: unless-stopped

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - smartnodule-api
    restart: unless-stopped

volumes:
  mlflow-data:
  model-data:
#'''